<a href="https://colab.research.google.com/github/vargas0721/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

A = np.array([[4,10,8],[10,26,26],[8,26,61]]) #creation of Matrix A
print(A)
print()
inv_A = np.linalg.inv(A) #creation of inverse Matrix A
print (inv_A)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [8]:
B = np.array([[44],[128],[214]]) #creation of Matrix B
print(B)

[[ 44]
 [128]
 [214]]


In [9]:
X=np.dot(inv_A,B)
print(X)

[[-8.]
 [ 6.]
 [ 2.]]


#Checking

In [6]:
A=np.dot(A,X)
print(A)

[[ 44.]
 [128.]
 [214.]]
