<a href="https://colab.research.google.com/github/vargas0721/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem 1**

In [22]:
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
X = np.linalg.inv(A).dot(B)
print(X)

[[13.]
 [57.]
 [19.]]


# **Problem 2**

In [27]:
import numpy as np
from scipy.linalg import solve
A=np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
print()
B=np.array([[5],[15],[-20]])
print(B)

#X=solve(A,B)
#print(X)


#Error of linalgerror : singular matrix
#This problem results in an error since the determinant is 0. As a result, the inverse of the matrix does not exist.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

[[  5]
 [ 15]
 [-20]]


# **Problem 3**

In [11]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8, 5, -6],[-12, -9, 12],[-3, -3, 5]])
print(A)
print()
w,v = np.linalg.eig(A)
print("The eigenvalues are: \n",w)
print()
print("The eigenvectors are: \n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The eigenvalues are: 
 [-1.  3.  2.]

The eigenvectors are: 
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
