<a href="https://colab.research.google.com/github/vargas0721/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Question 1**

In [15]:
import numpy as np 

A = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) 
print() 
print(A) 


[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


# **Question 2**

In [41]:
A = np.array ([[1,1,1,1,],[0,1,1,1,],[0,0,1,1,],[0,0,0,1]]) 
print()
print(A) 


[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


# **Question 3**

In [44]:
A = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(A)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


# **Question 4**

In [16]:
import numpy as np
C = np.array( [[1,2,3],[2,3,3],[3,4,-2]]) #create Matrix C
print(C)
print()
inv_C = np.linalg.inv(C) #create the inverse Matrix C
print (inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


# **Question 5**

In [17]:
C = np.array ([[1,2,3], [2,3,3], [3,4,-2]]) #create Matrix C
print(C)
print()
print (round(np.linalg.det(C))) #determinant of given matrix C from Question 4

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5


# **Question 6**

In [48]:
A = np.array([[5,4,1], [10,9,4], [10,13,15]])

B = np.array([[[3.4], [8.8], [19.2]]])

C = np.linalg.inv(A) @ B #root of the equation

print(C)

[[[0.2]
  [0.4]
  [0.8]]]
