<a href="https://colab.research.google.com/github/vargas0721/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practical Lab Exam 1**

In [10]:
#numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print()
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print()
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)
print()
D = np.array([[1,2],[3,4]])
print(D)
print()
dot = np.dot(A,B)
print(dot)
print()
print(D+D)
print()
print(2*C)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [3 4]]

[[22 28]
 [49 64]]

[[2 4]
 [6 8]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [11]:
import numpy as np
A = np.array([5, 3, -1])

print ("Size of array:", A.size)
print ("Type of array:", type(A))
print ("Shape or array:", A.shape)
print ("Dimension of array:", A.ndim)


Size of array: 3
Type of array: <class 'numpy.ndarray'>
Shape or array: (3,)
Dimension of array: 1
