<a href="https://colab.research.google.com/github/vargas0721/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix C


Question 1

In [33]:
import numpy as np
x = np.diag([1, 1, 1, 1])
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 2


In [34]:
import numpy as np
x = np.diag([1, 1, 1, 1,])
print(x)
print()
print(x+x)
print()

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]



Question 3

In [35]:
A = np.array([2,7,4])
B = np.array([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
